index:
   path: /
   controller: App\Controller\ProductController::list

product:
    path: /product
    controller: App\Controller\ProductController::list

details:
    path: /product/{sku}
    controller: App\Controller\ProductController::details

_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix:   /_error
