index:
   path: /
   controller: App\Controller\ProductController::list

product:
    path: /product
    controller: App\Controller\ProductController::list

details:
    path: /product/{sku}
    controller: App\Controller\ProductController::details
